### ISSUE TITLE
Do not commit all files to git

### ISSUE THREAD

**Issue by any626** [MiguelHuerta88/atm-system#5]
Add .class to gitignore and remove existing .class files from repo.

Looks like some files are specific to IDEs. Those should not be added to git as well.
http://stackoverflow.com/questions/11968531/what-to-gitignore-from-the-idea-folder

**Comment by MiguelHuerta88** [comment]
@any626 thanks for the comment. I'll take care of it tonight.

**Comment by illmatictime** [comment]
Thanks for the tip, bro!
