### ISSUE TITLE
Hashing vs Encrypting

### ISSUE THREAD

**Issue by any626** [MiguelHuerta88/atm-system#6]
Not 100% on this, but I believe you might want to hash the pin since it acts as a password.

**Comment by MiguelHuerta88** [comment]
@any626  you are absolutely 100% correct. Passwords are suppose to be hashed. I guess i completely forgot about that. My mistake. We will address this soon.

**Comment by illmatictime** [comment]
Thank you @any626, @MiguelHuerta88 is working on it. The feature should be finished before the weeks end.

**Comment by MiguelHuerta88** [comment]
Closing. Hashing pin now instead of encrypting.
